AFRAME.CONSTANTS = {
  MAX_LEVEL: 20,

  INSTRUCTION_BLOCK_SCALE: 0.90,
  INSTRUCTION_UNSELECTED_COLOR: 'white',
  INSTRUCTION_SELECTED_COLOR: 'yellow',
  INSTRUCTION_CURRENT_COLOR: 'blue',
  INSTRUCTION_LIBRARY_SIZE: 7,

  CODE_BLOCK_ROW_COUNT: 3,
  CODE_BLOCK_COL_COUNT: 4,
  CODE_BLOCK_SCALE: 0.95,
  CODE_BLOCK_SIZE: 1,

  GAME_BOARD_X_OFFSET: -5,

  CAPTION_TEXT_SIZE: 10,
  CAPTION_HEIGHT: 0.5,

  BOX_SCALE: 0.90,
  BOX_SIZE: 1,

  BORDER_COLOR: 'black',
  BORDER_COLOR_SELECTED: 'blue',

  BUTTON_WIDTH: 3,
  BUTTON_HEIGHT: 1,
  BUTTON_RADIUS: 0.1,

  NORTH_ROT: 180,
  WEST_ROT: -90,
  SOUTH_ROT: 0,
  EAST_ROT: 90,

  DIRECTION_ROT: {
    'north': 180,
    'east': 90,
    'south': 0,
    'west': -90
  },

  DIRECTION_DELTA: {
    'north': {row: -1, col: 0},
    'east': {row: 0, col: 1},
    'south': {row: 1, col: 0},
    'west': {row: 0, col: -1},
  },

  SHOULD_LIGHT: 8,
  LIT: 16,
  PROC_SIZE: 12,
  COLUMNS: 4,
  PROC_COUNT: 3,

  LIT_COLOR: '#FFFF00',
  LIT_ERROR_COLOR: '#FF0000',
  SHOULD_LIGHT_COLOR: '#00FFFF',
  GRAY_COLOR: '#AAAAAA',

  BUTTON_PLAY_COLOR: '#50a132',
  BUTTON_STOP_COLOR: '#FF0000',
  BUTTON_RESET_COLOR: '#0000FF',
  BUTTON_NEXT_LEVEL_COLOR: '#0000FF',

  DELAY_TO_ROBOT_DROP: 200,
  DELAY_TO_BOX_DROP: 1000,
  DELAY_BETWEEN_STEPS: 300,
  DELAY_TO_RESET: 1500,
  DELAY_AFTER_MOVE: 500,
  DELAY_AFTER_LIGHT: 500,

  STANDBY: 0,
  PLAY: 1,
  FAIL_FALL: 2,
  FAIL_LIGHT_INCORRECT: 3,
  FAIL_INCOMPLETE: 4,
  LEVEL_COMPLETE: 9,
  GAME_COMPLETE: 15,

};
